### ISSUE TITLE
Nullref in RainMeter.ctor

### ISSUE THREAD

**Issue by Garrakx** [Garrakx/Monkland#1]
NullReferenceException: Object reference not set to an instance of an object
(wrapper dynamic-method) HUD.RainMeter.orig_.ctor (HUD.RainMeter,HUD.HUD,FContainer) <0x0005e>
Monkland.Hooks.Menus.RainMeterHK.CtorHK (On.HUD.RainMeter/orig_ctor,HUD.RainMeter,HUD.HUD,FContainer) <0x0001e>
(wrapper dynamic-method) HUD.RainMeter.hook_.ctor_1382029696 (HUD.RainMeter,HUD.HUD,FContainer) <0x00021>
Monkland.Hooks.Menus.HUDHK.InitSleepHudHK (On.HUD.HUD/orig_InitSleepHud,HUD.HUD,Menu.SleepAndDeathScreen,HUD.Map/MapData,SlugcatStats) <0x0017c>
(wrapper dynamic-method) HUD.HUD.hook_InitSleepHud_222314880 (HUD.HUD,Menu.SleepAndDeathScreen,HUD.Map/MapData,SlugcatStats) <0x00027>
Menu.SleepAndDeathScreen.GetDataFromGame (Menu.KarmaLadderScreen/SleepDeathScreenDataPackage) <0x00083>
RainWorldGame.CommunicateWithUpcomingProcess (MainLoopProcess) <0x00ec6>
Monkland.Hooks.ProcessManagerHK.SwitchMainProcessHK (On.ProcessManager/orig_SwitchMainProcess,ProcessManager,ProcessManager/ProcessID) <0x001f9>
(wrapper dynamic-method) ProcessManager.hook_SwitchMainProcess_1833668096 (ProcessManager,ProcessManager/ProcessID) <0x00021>
ProcessManager.Update (single) <0x00187>
RainWorld.Update () <0x00027>

**Comment by metnias** [comment]
I tried using orig_ctor if possible, but that causes NullRefException when the owner is not Player (but MultiplayerSleepAndDeathScreen)
So I decided not to call the original ctor when that's the case.
Pushed the fix and it's resolved.
