### ISSUE TITLE
FutileException: Couldn't find element named 'LegsA7'. 

### ISSUE THREAD

**Issue by Garrakx** [Garrakx/Monkland#10]
FutileException: Couldn't find element named 'LegsA7'. 
Use Futile.atlasManager.LogAllElementNames() to see a list of all loaded elements names
FAtlasManager.GetElementWithName (System.String elementName)
PlayerGraphics.DrawSprites (.SpriteLeaser sLeaser, .RoomCamera rCam, Single timeStacker, Vector2 camPos)
RoomCamera+SpriteLeaser.Update (Single timeStacker, .RoomCamera rCam, Vector2 camPos)
RoomCamera.DrawUpdate (Single timeStacker, Single timeSpeed)
RainWorldGame.GrafUpdate (Single timeStacker)
MainLoopProcess.RawUpdate (Single dt)
RainWorldGame.RawUpdate (Single dt)
ProcessManager.Update (Single deltaTime)
RainWorld.Update ()

**Comment by metnias** [comment]
this means Player.animationFrame is set to 7 when it's not supposed to do that.
none of the code in Monkland access Player.animationFrame.
the only time Player.animationFrame is being set (excluding ctor) is in UpdateAnimation and UpdateBodyMode, both of which is not hooked by Monkland.
and those two are called from MovementUpdate, which is also not hooked by Monkland.

so yeah, I doubt this is our fault. unless you elaborate. I cannot investigate this issue farther just from that log.

**Comment by Garrakx** [comment]
This is def something caused by Monkland. 

FutileException: Couldn't find element named 'LegsA7'. 
Use Futile.atlasManager.LogAllElementNames() to see a list of all loaded elements names
FAtlasManager.GetElementWithName (System.String elementName)
PlayerGraphics.DrawSprites (.SpriteLeaser sLeaser, .RoomCamera rCam, Single timeStacker, Vector2 camPos)
RoomCamera+SpriteLeaser.Update (Single timeStacker, .RoomCamera rCam, Vector2 camPos)
RoomCamera.DrawUpdate (Single timeStacker, Single timeSpeed)
RainWorldGame.GrafUpdate (Single timeStacker)
MainLoopProcess.RawUpdate (Single dt)
RainWorldGame.RawUpdate (Single dt)
ProcessManager.Update (Single deltaTime)
RainWorld.Update ()
